#version 450
#extension GL_EXT_nonuniform_qualifier : require

#include "bindless.glsl"
#include "lygia/generative/psrdnoise.glsl"
#include "common.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(push_constant) uniform CloudVolumeGenPushConstants {
	vec4  cameraPos;            // x, y, z = camera position
	uvec4 cascadeStorageIdx;    // x, y, z = storage bindless indices for cascades 0, 1, 2
	vec4  cascadeExtents;       // x = 20000, y = 80000, z = 320000, w = 15000 (vertical span)
	vec4  cascadeCenterPos[3];  // x, z = center world position for cascade 0, 1, 2
	ivec4 cascadeGridOffset[3]; // x, y = toroidal grid offset (voxels) for cascade 0, 1, 2
	uint  forceRegeneration;
} push;

vec3 hash33(vec3 p) {
	p = fract(p * vec3(443.897, 441.423, 437.195));
	p += dot(p, p.yxz + 19.19);
	return fract((p.xxy + p.yxx) * p.zyx);
}
float hash13Tile(in vec3 pos, in vec3 period) {
	if (period.x > 0.0) pos = mod(pos, period);
    pos  = fract(pos * vec3(.1031, .1030, .0973));
    pos += dot(pos, pos.zyx + 31.32);
    return fract((pos.x + pos.y) * pos.z);
}

float alligator(vec3 position, float gridsize, vec3 seed, bool tiling) {

    // Only int gridsize if it needs to tile
    if (tiling) gridsize = round(gridsize);
    gridsize = max(1.0, gridsize);

    position *= gridsize;
    position += hash33(vec3(seed)); // offset so FBM grids do not align

    vec3 id = floor(position);
    vec3 grid = position - id; // fract(position)

    float densest = 0.0;
    float secondDensest = 0.0;

    // Search the current cell and its neighbors (3x3x3)
    for (int x = -1; x <= 1; ++x)
    for (int y = -1; y <= 1; ++y)
    for (int z = -1; z <= 1; ++z) {

        vec3 offset = vec3(x, y, z);
        vec3 cell = id + offset;

        // Wrap cell coordinates to make the noise tile over [0,1]
        if (tiling) cell = mod(cell, gridsize);

         // Offset the hash input to avoid hashing zero coordinates
        cell += vec3(seed);

        // Get random center of the Cell
        vec3 center = hash33(cell) + offset;

        float dist = distance(grid, center);

        // 'if(dist < 1.0)' doesn't have any effect and doesn't improve
        // performance. See: https://www.shadertoy.com/view/MflGWM

        // Get random density scaled by the distance to the random point
        float density = hash13Tile(cell, vec3(gridsize)) * smoothstep(0, 1, 1.0 - dist);

        // Keep track of the two largest density values
        if (densest < density) {
            secondDensest = densest;
            densest = density;

        } else if (secondDensest < density) {
            secondDensest = density;
        }
    }
    // The alligator noise is the difference between the two largest densities
    return densest - secondDensest;
}

// Fractal Brownian motion applied to noise
float fractal(vec3 position, float gridsize, int octaves,
              float lacunarity, float persistence, bool tiling) {

    // For Amplitude math see: www.desmos.com/calculator/xgqeepapwn
    float amplitude = 1.0;
    float amplitudeSquaredSum = 0.0;
    float result = 0.0;
    vec3 seed = vec3(421); // can be any positive integer

    // Accumulate detail layers
    for(int i = 0; i < max(1, octaves); ++i) {
        // sample noise and apply amplitude
        result += alligator(position, gridsize, seed, tiling) * amplitude;
        amplitudeSquaredSum += amplitude * amplitude;

        // Increment for next iteration
        gridsize *= lacunarity;
        amplitude *= persistence;
        seed += gridsize;
    }

    // Restore variance lost by averaging
    // FabriceNeyret2 https://www.shadertoy.com/view/4dcSDr
    return result / sqrt(amplitudeSquaredSum);
}


void main() {
	uvec3 vox = gl_GlobalInvocationID;
	if (vox.x >= 256 || vox.y >= 256 || vox.z >= 256) {
		return;
	}

	for (int c = 0; c < 3; ++c) {
		uint storageIdx = push.cascadeStorageIdx[c];
		if (storageIdx == 0xFFFFFFFFu) {
			continue;
		}

		// Toroidal voxel index calculation
		ivec3 localVox = (ivec3(vox) + push.cascadeGridOffset[c].xyz) % 256;
		if (localVox.x < 0) localVox.x += 256;
		if (localVox.y < 0) localVox.y += 256;
		if (localVox.z < 0) localVox.z += 256;

		float hExtent = push.cascadeExtents[c];
		float vSpan = push.cascadeExtents.w; // 15000m
		float baseAlt = 1000.0;             // 1km in the air

		// World position corresponding to this voxel
		vec3 voxelNorm = (vec3(vox) / 256.0) - vec3(0.5, 0.0, 0.5);
		vec3 worldPos = vec3(
			push.cascadeCenterPos[c].x + voxelNorm.x * hExtent,
			baseAlt + voxelNorm.y * vSpan,
			push.cascadeCenterPos[c].z + voxelNorm.z * hExtent
		);

		// Basic noise/procedural density
		float n1 = psrdnoise(worldPos/vec3(5000), vec3(0.0), 0.0);
		float n2 = psrdnoise(worldPos/vec3(100000, 5000, 100000), vec3(0.0), 1.0);
		// float density = smoothstep(0.850, 1.0, smoothstep(0.5, 1.0, n2)*(n1+n2));
		float density = step(0.0, n2)*remap(n1, n2, 1.0, 0.0, 1.0);
		// float density = smoothstep(0.25, 1.0, n2) * fractal(worldPos, 32, 3, 1.8, 0.47, false);

		// density *= smoothstep(0.1, 0.15, voxelNorm.y) * (1.0 - smoothstep(0.9, 1.0, voxelNorm.y));
		imageStore(uImages3DGenericWrite[nonuniformEXT(storageIdx)], ivec3(localVox), vec4(density, 0.0, 0.0, 1.0));
	}
}
