#version 460 core
#include "bindless.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct IndirectCommand {
	uint groupCountX;
	uint groupCountY;
	uint groupCountZ;
};

layout(std430, set = 1, binding = 3) buffer IndirectCommandBuffer {
	IndirectCommand uIndirectCommand;
};

void main() {
	uIndirectCommand.groupCountX = 0;
	uIndirectCommand.groupCountY = 1;
	uIndirectCommand.groupCountZ = 1;
}
