#version 460 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#include "../bindless.glsl"
#include "../helpers/noise.glsl"

layout(push_constant) uniform CloudBakePushConstants {
	uint weatherStorageIdx;
	uint minMaxStorageIdx;
	uint volumeStorageIdx;
	float worldScale;
	float cloudCoverage;
	float cloudThickness;
	float time;
	uint padding;
} push;

void main() {
	ivec3 voxel = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 size = imageSize(uImages3D[nonuniformEXT(push.volumeStorageIdx)]);
	if (voxel.x >= size.x || voxel.y >= size.y || voxel.z >= size.z) return;

	vec3 p = vec3(voxel) / vec3(size);

	float noiseVal = dot_noise_fbm(p * 8.0, 4);
	float worleyWide = cross_noise_fbm(p * 4.0, 3);
	float worleyMedium = cross_noise_fbm(p * 8.0, 3);
	float worleySmall = cross_noise_fbm(p * 16.0, 2);

	imageStore(uImages3D[nonuniformEXT(push.volumeStorageIdx)], voxel, vec4(noiseVal, worleyWide, worleyMedium, worleySmall));
}
