#version 460 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#include "../bindless.glsl"
#include "../common.glsl"

layout(set = 1, binding = 3, rgba16f) uniform image3D outVolume;

layout(push_constant) uniform Cloud3DVolumeBakePushConstants {
	uint outVolumeIdx;
} push;

void main() {
	ivec3 voxel = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 size = imageSize(outVolume);
	if (voxel.x >= size.x || voxel.y >= size.y || voxel.z >= size.z) return;

	vec3 p = vec3(voxel) / vec3(size);

	float noiseVal = dot_noise_fbm(p * 8.0, 4.0, 0.0);
	float worleyWide = length(cross_noise_fbm(p * 4.0, 3.0, 0.0));
	float worleyMedium = length(cross_noise_fbm(p * 8.0, 3.0, 0.0));
	float worleySmall = length(cross_noise_fbm(p * 16.0, 2.0, 0.0));

	imageStore(outVolume, voxel, vec4(noiseVal, worleyWide, worleyMedium, worleySmall));
}
